### ISSUE TITLE
Chocolatey doesn't install properly in 3rd script

### ISSUE THREAD

**Issue by windowz414** [ucoruh/cpp-cmake-ctest-template#2]
So, Choco seems to install properly, however when I check C:\ProgramData\chocolatey, it's completely empty, which causes the install script to not work properly.

**Comment by ucoruh** [comment]
To address the issue where your C:\ProgramData\chocolatey folder is empty, you might be facing problems related to failed installation or permission restrictions. It is essential to run the script with administrative privileges for it to work correctly.

Here are the steps to follow:

- Open Command Prompt (cmd.exe) as an administrator.
- Navigate to the directory where your script is located.
- Run the script.

The script checks for the presence of choco.exe in the "%ProgramData%\Chocolatey\bin" directory to determine if Chocolatey is installed. If you encounter any issues, it's likely due to failed installation or permission problems. Make sure to execute the script with administrative permissions to avoid these issues.

**Comment by ucoruh** [comment]
Also script is updated, use optimized version https://github.com/ucoruh/cpp-cmake-ctest-template/blob/main/3-install-package-manager.bat
